### ISSUE TITLE
add comments / release notes

### ISSUE THREAD

**Issue by dbachelder** [testfairy/testfairy-gradle-plugin#1]
I'd like to be able to attach notes at upload time. I have a file I keep updated. For test flight I was grabbing a chunk of it and sending it along with the apk and my testers would see it in the email.

**Comment by john-stemberger** [comment]
Would it be possible to add a via the testfairyConfig in a similar manner to the way you can provide a signing key when buildingan apk?

I.E. similar to how you can specify 
storePassword System.console().readLine("\nKeystore password: ")
 in the android signing config could we add 
changeLog System.console().readline("\nChange log message or enter for blank:")
