### ISSUE TITLE
Could not locate jarsigner, please update java.home property error in 1.3 

### ISSUE THREAD

**Issue by ihal20** [testfairy/testfairy-gradle-plugin#11]
Seems that java 1.6 with version 1.3 generates a "Could not locate jarsigner, please update java.home property".  Seems the locateJarsigner is the root of the issue.  Should the jarsigner path also have bin appended to it?
     <code>
     String jarsigner = java_home + "/bin/jarsigner" + ext
    </code>
 instead of
<code>
     String jarsigner = java_home + "/jarsigner" + ext
    </code>

**Comment by testfairy** [comment]
Support has been added so it now looks for jarsigner in more directories. Future versions will remove this dependency altogether.
