### ISSUE TITLE
TestFairy build command always failed

### ISSUE THREAD

**Issue by ducn** [testfairy/testfairy-gradle-plugin#31]
Hi,

I built the app with testfairy today with this command: 
./gradlew testfairyDebug

but it always displayed failed message like this :
com/testfairy/uploader/SdkEnvironment : Unsupported major.minor version 51.0

What went wrong ? how do I fix this ?

**Comment by testfairy** [comment]
Hey @ducn. Is this issue still relevant?
Also, the new Gradle plugin, version 1.12 solves this. You just need to recompile.
