### ISSUE TITLE
peer not authenticated

### ISSUE THREAD

**Issue by jonneymendoza** [testfairy/testfairy-gradle-plugin#34]
Hi.

i get this error when using testFairy plugin/

any idea?

**Comment by gmegidish** [comment]
Can you run with --debug and see if you're getting this error because of 'apply testfairy' or when it's uploading the build to testfairy?

Is the time on your computer set properly?

Are you behind some corporate firewall?

**Comment by jonneymendoza** [comment]
here is full stacktrace with debug enabled

11:20:13.545 [DEBUG] [org.apache.http.client.protocol.RequestAuthCache] Auth cache not set in the context
11:20:13.545 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Sending request: CONNECT app.testfairy.com:443 HTTP/1.1
11:20:13.546 [DEBUG] [org.apache.http.headers] >> CONNECT app.testfairy.com:443 HTTP/1.1
11:20:13.546 [DEBUG] [org.apache.http.headers] >> Host: app.testfairy.com
11:20:13.546 [DEBUG] [org.apache.http.headers] >> Proxy-Connection: Keep-Alive
11:20:13.547 [DEBUG] [org.apache.http.headers] >> User-Agent: Apache-HttpClient/4.1.1 (java 1.5)
11:20:13.901 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Receiving response: HTTP/1.0 200 Connection established
11:20:13.901 [DEBUG] [org.apache.http.headers] << HTTP/1.0 200 Connection established
11:20:13.902 [DEBUG] [org.apache.http.client.protocol.ResponseProcessCookies] Cookie spec not specified in HTTP context
11:20:13.903 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Tunnel to target created.
11:20:14.066 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Connection closed
11:20:14.067 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Connection shut down
11:20:14.067 [DEBUG] [org.apache.http.impl.conn.SingleClientConnManager] Releasing connection org.apache.http.impl.conn.SingleClientConnManager$ConnAdapter@47c15468
11:20:14.068 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':myProject:testfairyProductionRelease'
11:20:14.068 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :myProject:testfairyProductionRelease FAILED
11:20:14.069 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :myProject:testfairyProductionRelease (Thread[main,5,main]) completed. Took 0.793 secs.
11:20:14.069 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 4.572 secs, idle: 0.011 secs
11:20:14.078 [ERROR] [org.gradle.BuildExceptionReporter] 
11:20:14.078 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
11:20:14.078 [ERROR] [org.gradle.BuildExceptionReporter] 
11:20:14.078 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
11:20:14.078 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':myProject:testfairyProductionRelease'.
11:20:14.078 [ERROR] [org.gradle.BuildExceptionReporter] > peer not authenticated
11:20:14.079 [ERROR] [org.gradle.BuildExceptionReporter] 
11:20:14.079 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
11:20:14.079 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
11:20:14.079 [LIFECYCLE] [org.gradle.BuildResultLogger] 
11:20:14.079 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
11:20:14.079 [LIFECYCLE] [org.gradle.BuildResultLogger] 
11:20:14.080 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 11.118 secs

**Comment by gmegidish** [comment]
@jonneymendoza, can you please try adding 
serverEndpoint "http://app.testfairy.com"
in the testfairy section in your build.gradle?

Let's see if removing https works. We haven't received such a problem from others, so I'm debugging with you :) Please let me know how it works.

**Comment by dawidhyzy** [comment]
I've the same issue and adding serverEndpoint "http://app.testfairy.com" doesn't help.

**Comment by gmegidish** [comment]
Can you please run gradle with --stacktrace and send output to support@testfairy.com ?

**Comment by gmegidish** [comment]
Is this still relevant?

**Comment by dawidhyzy** [comment]
It's fixed. I've send a feedback in email.

**Comment by hmorillo** [comment]
I've got the same problem. Do you have de feedback?

**Comment by gmegidish** [comment]
Can you please send stacktrace to support@testfairy.com?
