### ISSUE TITLE
Need ability to specify signing algorithms

### ISSUE THREAD

**Issue by tomb50** [testfairy/testfairy-gradle-plugin#37]
Hi,

I am unable to upload a signed apk due to the signApk function hardcoding the digestalg and/or sigalg value(s) to methods that our keystore are not compatible with. Our keystore contents cannot be signed with MD5withRSA, it is likely that a new keystore should be created which supports this new default algorithm, but I don't really want to have to.

The exact error is:

<jarsigner_path>/jarsigner -keystore /Users/tombeadman/IdeaProjects/rentalmobile/keystore/keystore -storepass <password> -keypass <password> **-digestalg SHA1 -sigalg MD5withRSA** <build_path>/build/tmp/packageRelease/testfairy-rm-receive-crosshire-release-unaligned.apk.temp e-result
jarsigner error: java.security.SignatureException: private key algorithm is not compatible with signature algorithm

Letting the keystone infer the lags by omitting those above args allows signing successfully.

I've done a commit on a forked branch but I am unfamiliar with writing Gradle plugins so have not been able to build or test

Are you able to advise on whether this approach is appropriate, and how I may able to test this, and if successful is it appropriate for a pull request?

https://github.com/tomb50/testfairy-gradle-plugin/commit/a241a2abe6a1d4bb281d40216ad07bcdeee87fc1

Thanks
Tom

**Comment by IonutGavris** [comment]
+1

**Comment by gmegidish** [comment]
Instrumentation has been deprecated in version 2.0. Please use our TestFairy SDK. Thanks!
