### ISSUE TITLE
Get uri to download app from Gradle

### ISSUE THREAD

**Issue by dant3** [testfairy/testfairy-gradle-plugin#39]
Hello,

Thanks for wonderful service.
I'm trying to create a gradle task which will write a message to slack with notification that new build was uploaded to TF, so people can go and play with it. I added a task which always run after running upload with testfairyXXX task. That I'm missing now is a way to get a link after testfairyXXX task completes. Is this possible to do that?

**Comment by gmegidish** [comment]
Hey Dant3,

When running "gradle testfairyRelease", it prints out the link to the build page on TestFairy. You can just grab the output. This is what you want.

The code is here: https://github.com/testfairy/testfairy-gradle-plugin/blob/master/src/main/groovy/com/testfairy/plugins/gradle/TestFairyPlugin.groovy#L143

Alternatively, you can see up a webhook for "upload" event, use automatic notifications in email when uploading and receive the url there, or use the REST API and query the latest build.

I think just grepping gradle's output is the easiest to accomplish.
