### ISSUE TITLE
removeSignature() does not seem to work

### ISSUE THREAD

**Issue by antonyt** [testfairy/testfairy-gradle-plugin#4]
The `removeSignature()` step does not seem to work. Pausing the executing after `removeSignature()` and looking at the intermediary APK shows that it is still signed, i.e. it still has its `META-INF` files intact. Running the zip command manually to delete `META-INF` files seem to work, but running it from the script fails. The zip command returns an error code '12' - i.e. it had no work to do.

The META-INF files are not removed before re-signing, but the script continues to sign the APK with the alternative signing config. Signature verification fails after this happens (and the new, re-signed APK is not uploaded).

The project needs to have a custom signing config for this code path to be hit. This happens for me using the gradle wrapper on OS X (10.8.5).

**Comment by testfairy** [comment]
Version 1.12 doesn't need external zip tool anymore and works with pure java. This works on Windows as well as Mac/Linux.
