### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by dant3** [testfairy/testfairy-gradle-plugin#40]
I'm doing iOS build automation for CI environment using gradle. Is this possible to somehow use this plugin to upload iOS app build to TestFairy? I'm ready to do this manually in my project if thats required, but was thinking that I could reuse some pieces of code of this project, by just calling some methods of this plugin directly?

**Comment by vijaysharm** [comment]
Hi, could you describe your workflow? Do you use a gradle plugin to perform iOS builds with gradle?

**Comment by dant3** [comment]
Yes, I'm building my iOS project with Gradle for CI using this plugin: https://github.com/openbakery/gradle-xcodePlugin

**Comment by gmegidish** [comment]
@dant3, unfortunately we have no plans of supporting iOS in Gradle. You can run 'curl' directly from within your tasks. Please visits https://docs.testfairy.com for more information about uploading using curl.
