### ISSUE TITLE
Couldn't sign

### ISSUE THREAD

**Issue by GokhanArik** [testfairy/testfairy-gradle-plugin#48]
I started getting this error in my project today.

`Could not jarsign sampleAppNameQa-release-unaligned.apk.temp, used this command: [/Library/Java/JavaVirtualMachines/jdk1.8.0_51.jdk/Contents/Home/bin/jarsigner, ......`

Any idea about that?

**Comment by jhbruhn** [comment]
I think this is related to the ZipAlign Task not being executed anymore (Changes in Android SDK or gradle plugin I think).

**Comment by jtietema** [comment]
@GokhanArik there was an outage with TestFairy on their server side that caused this issue. The plugin post the APK to TestFairy, which then adds the extra monitoring tools into the app and then the plugin downloads the APK again and signs it with the local key. Last week there was a problem that caused the server to send back an empty file.

**Comment by GokhanArik** [comment]
@jtietema Yes it started working the day after that. Thanks
