### ISSUE TITLE
Could not locate jarsigner, please update java.home property error in the last version (1.+) and JDK 1.7

### ISSUE THREAD

**Issue by fernandosg** [testfairy/testfairy-gradle-plugin#50]
I am stuck with a problem in the last 20 minutes.
After search in the list issues, and try the posible solutions (move the jarsigner), nothing is working.
I follow the steps for installation, so i believe that i am using the last versión of the plugin (
        classpath 'com.testfairy.plugins.gradle:testfairy:1.+').
When i run gradlew the error is the next one:
- What went wrong:
  A problem occurred evaluating project ':app'.
  > Failed to apply plugin [id 'testfairy']
  > Could not locate jarsigner, please update java.home property

I have the jdk 1.7.0_79 and Windows 10.
If this error was fixed in previous versión of the library of TestFairy , please let me know the exactly version if this may be is the problema.
This is the gist of the complete log: https://gist.github.com/fernandosg/1d30e5f05338e28c43abf22d84c7468e#file-issue-testfairy-txt-L41

**Comment by gmegidish** [comment]
We have deprecated the use of instrumentation. When using the sdk, jarsigner is no longer needed. Please use version 2.+
