### ISSUE TITLE
Problem with upload

### ISSUE THREAD

**Issue by matbos** [testfairy/testfairy-gradle-plugin#53]
Hi,

I have a problem with uploading the apk to the TestFairy. Whenever I build on the CI and use the plugin to upload it to the TestFairy it returns the following error:

```
Execution failed for task ':app:testfairyStageRelease'.
[Gradle failure report] > Failed with json: {"status":"fail","code":1,"message":"Could not find build with versions , <my_version> and package name <my_package>","uploaded_via":"api"}
```
And this is my config:
```
testfairyConfig {
    apiKey "my_key"
    testersGroups "devs,friends"
    notify true
    uploadProguardMapping true
    iconWatermark true
}
```
Per [TestFairy docs](https://docs.testfairy.com/API/Upload_API.html) I should have a missing parameter but I can't find any missing and the apk is properly uploaded and can be download by testers.

Did you encounter such an error before or can you guide me to what may be wrong(I am happy to help to do a PR if necessary)?

**Comment by NehaMadiwal** [comment]
Facing the same issue. Build is getting uploaded but task fails with the above mentioned error.

**Comment by giltsl** [comment]
Hi @matbos , @NehaMadiwal, this kind of error shouldn't happen to you, 
Can you please contact support@tesfairy.com or https://app.testfairy.com/contact so we can get more information and help you to solve the problem.
