### ISSUE TITLE
gradle testDevelopDebug runs testfairyUpload

### ISSUE THREAD

**Issue by flocsy** [testfairy/testfairy-gradle-plugin#58]
For some reason whenever I run ./gradlew testDevelopDebug it also runs testfairyDevelopDebug. I don't want to waste time and badwidth on that. However today testfairyDevelopDebug also fails 80% of the time and this breaks all our builds.

**Comment by giltsl** [comment]
Hi @flocsy,
TestFairy tasks should not run unless you will call it.
What is `testDevelopDebug` task? Can you maybe share your `build.gradle`.

Regarding the build failures, I need to know your testfairy username and project name. 
You can send us the information via support.

**Comment by flocsy** [comment]
Hi @giltsl,

The upload failures were caused by a network problem in out system.

testDevelopDebug is the default build when (as in most apps) you have "develop" flavor and "debug" buildType. When we run ./gradlew test it runs testDevelopDebug. I'll send you the other information you requested to your mail.
