### ISSUE TITLE
Could not jarsign /tmp/testfairy-app-debug-local-0.1.9999.apk

### ISSUE THREAD

**Issue by vilvic** [testfairy/testfairy-gradle-plugin#6]
After running gradle testfairyDebug I get the following error;

> Could not jarsign /tmp/testfairy-app-debug-local-0.1.9999.apk, used this command:
  jarsigner -keystore /home/john/.android/debug.keystore -storepass android /tmp/testfairy-app-debug-local-0.1.9999.apk AndroidDebugKey -verbose

On closer inspection the file in the /tmp/testfairy-app-debug-local-0.1.9999.apk file is only 4402 bytes.  I opened the file and it's HTML.  I appears to be the testfairy login page.

**Comment by rafaelekol** [comment]
We had same error, it was causing by bad DNS proxy(some google sites couldn't open).
Solved this problem by fixing our local DNS proxy.

**Comment by gmegidish** [comment]
Strict Mode has been long solved (about a year ago.) I'm closing this bug.
