### ISSUE TITLE
Version 3.4 fails to find APK

### ISSUE THREAD

**Issue by nick-fedesna** [testfairy/testfairy-gradle-plugin#65]
Gradle 5.4.1
AGP: 3.5.3

Didn't change any configuration and because you suggest `3+` for your dependency, project was upgraded to 3.4 (released yesterday it seems) and get the following error:

`Can't find any APK file to upload.`
`java.io.IOException: Apk not found.`

IDK what changed, and perhaps this works on more up-to-date Gradle/AGP, but I don't have time to check that now, will check that next week when I get another suggestion to update those.

NOTE: using `+` for dependency is now a discouraged practice and I would suggest you stop recommending that ASAP

**Comment by diegoperini** [comment]
@nick-fedesna Thanks for reporting this bug and sorry for the inconvenience. 

We suggest `MAJOR.+` minor, hoping that nothing will break between minor releases. This apparently indicates a bug on our side which we will look into as soon as possible. In the meantime, you can rollback to 3.3 to avoid the issue. I will post a postmortem here once a fix is ready.

To be able to speed up the debugging, can you share a few details like below?

1. The exact command (including the application variant name) that gives this error.
2. The APK's absolute path which this plugin couldn't find.
3. Any other stacktrace entry if exists any.
4. Android Studio and project's gradle version

**Comment by diegoperini** [comment]
Hi @nick-fedesna ,
Can you try 3.5 and see if it solves your issue?
